name: hieronymus
services:
  web:
    cpu_shares: 90
    command: []
    container_name: web
    deploy:
      resources:
        limits:
          memory: "4096M"
    environment:
      HOME: /app/$AppID
      NODE_ENV: production
      POSTGRES_HOST: host.docker.internal
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:
      CASSETTE_SERVER: true
      BACKUP_DIR: /app/backups
    hostname: web
    image: ghcr.io/beesnestinc/hieronymus/hieronymus-web:v2.0.0
    init: true
    ports:
      - target: 3010
        published: "3010"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/backups
        target: /app/backups
    working_dir: /app/hieronymus
    networks:
      - hieronymus
    extra_hosts:
      - host.docker.internal:172.30.0.1
    privileged: false
    x-casaos:
      ports:
        - container: "3010"
          description:
            en_US: ""
networks:
  hieronymus:
    name: hieronymus
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
x-casaos:
  architectures:
    - amd64
    - arm64
  main: web
  author: BeesNestLLC
  category: 会計
  description:
    ja_JP: Hieronymusは零細企業用のオープンソースERPシステムです。
    en_US: Hieronymus is an open source ERP system for small businesses.
  developer: BeesNestLLC
  icon: https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/public/icon-192x192.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E8%87%AA%E7%A4%BE%E6%83%85%E5%A0%B1%E3%81%AE%E7%99%BB%E9%8C%B2.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E4%BB%95%E8%A8%B3%E6%97%A5%E8%A8%98%E5%B8%B3.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E6%8C%AF%E6%9B%BF%E4%BC%9D%E7%A5%A8%E5%85%A5%E5%8A%9B.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E5%85%83%E5%B8%B3.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E5%8B%98%E5%AE%9A%E7%A7%91%E7%9B%AE%E7%AE%A1%E7%90%86.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E6%AE%8B%E9%AB%98%E8%A9%A6%E7%AE%97%E8%A1%A8.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E8%A8%BC%E6%86%91%E4%B8%80%E8%A6%A7.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E8%A8%BC%E6%86%91%E7%99%BB%E9%8C%B2.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E9%8A%80%E8%A1%8C%E5%85%83%E5%B8%B3.png
  index: /
  tagline:
    ja_JP: Hieronymusは零細企業用のオープンソースERPシステムです。
  thumbnail: https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E4%BB%95%E8%A8%B3%E6%97%A5%E8%A8%98%E5%B8%B3.png
  port_map: "3010"
  scheme: http
  title:
    en_US: Hieronymus
    ja_JP: Hieronymus
