name: hieronymus
services:
  web:
    cpu_shares: 90
    command: []
    container_name: web
    deploy:
      resources:
        limits:
          memory: 7811M
    environment:
      - HOME=/app/$AppID
      - NODE_ENV=production
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_USER=hieronymus
      - POSTGRES_PASSWORD=hieronymus
      - POSTGRES_DATABASE=hieronymus
      - CASSETTE_SERVER=true
    hostname: web
    image: ghcr.io/beesnestinc/hieronymus/hieronymus-web:v1.1.0
    init: true
    ports:
      - target: 3010
        published: "3010"
        protocol: tcp
    restart: always
    working_dir: /app/hieronymus
    networks:
      - hieronymus
    extra_hosts:
      - host.docker.internal:172.30.0.1
    privileged: false
    x-casaos:
      ports:
        - container: "3010"
          description:
            en_us: ""
networks:
  hieronymus:
    name: hieronymus
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
x-casaos:
  architectures:
    - amd64
    - arm64
  main: web
  author: BeesNestLLC
  category: 会計
  description:
    ja_jp: Hieronymusは零細企業用のオープンソースERPシステムです。
    en_us: Hieronymus is an open source ERP system for small businesses.
  developer: BeesNestLLC
  icon: https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/public/icon-192x192.png
  index: /
  tagline:
    ja_jp: Hieronymusは零細企業用のオープンソースERPシステムです。
  port_map: "3010"
  scheme: http
  title:
    en_us: Hieronymus
    ja_jp: Hieronymus
