name: hieronymus
services:
  web:
    cpu_shares: 90
    command: []
    container_name: web
    deploy:
      resources:
        limits:
          memory: "4096M"
    environment:
      HOME: /app/$AppID
      NODE_ENV: production
      POSTGRES_HOST: host.docker.internal
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:
      CASSETTE_SERVER: true
      BACKUP_DIR: /app/backups
    hostname: web
    image: ghcr.io/beesnestinc/hieronymus/hieronymus-web:v2.0.0
    init: true
    ports:
      - target: 3010
        published: "3010"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/backups
        target: /app/backups
    working_dir: /app/hieronymus
    networks:
      - hieronymus
    extra_hosts:
      - host.docker.internal:172.30.0.1
    privileged: false
    x-casaos:
      ports:
        - container: "3010"
          description:
            en_us: ""
networks:
  hieronymus:
    name: hieronymus
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
x-casaos:
  architectures:
    - amd64
    - arm64
  main: web
  author: BeesNestLLC
  category: 会計
  description:
    ja_jp: | 
      ## Hieronymusは中小企業用のオープンソースERPシステムです。
      https://github.com/BeesNestInc/hieronymus

      ### 機能
      - 基本的な会計機能(財務会計)
      - 新電帳法対応の証票管理機能
      - 顧客管理機能
      - 役職員管理機能
      - カスタムメニュー作成機能
      - 案件管理機能
      - 品目管理機能
      - 権限設定機能
      - 取引管理機能
      - 各種帳票の出力機能
      - データバックアップ＆復元機能
      - 推移表

      ### 使い始めに
      初期アカウント等は設定されていません。 初期ログインの時に自分でユーザ登録を行ってから使って下さい。
      ログイン後、ホーム画面上の自社情報より自社情報を作成してください。
      ![初期セットアップ](https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/documents/images/%E8%87%AA%E7%A4%BE%E6%83%85%E5%A0%B1%E3%81%AE%E7%99%BB%E9%8C%B2.png)

    en_us: Hieronymus is an open source ERP system for small businesses.
  developer: BeesNestLLC
  icon: https://cdn.jsdelivr.net/gh/beesnestinc/hieronymus@main/public/icon-192x192.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-6.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-7.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-8.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-9.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-10.png
    - https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/screenshot-11.png
  index: /
  tagline:
    ja_jp: Hieronymusは中小企業用のオープンソースERPシステムです。
    en_us: Hieronymus is an open source ERP system for small businesses.
  thumbnail: https://cdn.jsdelivr.net/gh/beesnestinc/CassetteOS-AppStore@main/Apps/Hieronymus/thumbnail-hieronymus.png
  port_map: "3010"
  scheme: http
  title:
    en_US: Hieronymus
    ja_JP: Hieronymus
